name: "main"
on: [ push, workflow_dispatch ]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: nixbuild/nix-quick-install-action@v19
      with:
        nix_conf: experimental-features = nix-command flakes
    - run: |
        git clone --depth=1 https://github.com/mlyxshi/flake.git
        cd flake
        mkdir install
        for host in $(nix flake show --json | jq '.nixosConfigurations|keys[]' | tr -d '"'); do
          SYSTEM_CLOSURE=$(nix eval --raw .#nixosConfigurations.$host.config.system.build.toplevel)
          echo $SYSTEM_CLOSURE > install/$host
        done
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        files: flake/install/*
